name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        if: ${{ startsWith(github.event.head_commit.modified, 'FirstApp/') || startsWith(github.event.head_commit.modified, 'SecondApp/') || startsWith(github.event.head_commit.modified, 'Modules/') }}
        env:
          REGISTRY: ghcr.io
          REPO_NAME: Shahid199578/monorepo
        run: |
          if [[ ${{ startsWith(github.event.head_commit.modified, 'Modules/') }} == 'true' ]]; then
            cp -r Modules/* FirstApp/
            cp -r Modules/* SecondApp/
          fi

          docker buildx create --use
          docker buildx build --platform linux/amd64 --push --tag ${{ env.REGISTRY }}/${{ env.REPO_NAME }}:latest ./FirstApp
          docker buildx build --platform linux/amd64 --push --tag ${{ env.REGISTRY }}/${{ env.REPO_NAME }}:latest ./SecondApp
