name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker-container
          buildkitd-flags: --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host
          install: false
          use: true
        env:
          DOCKER_BUILDKIT: 1

      - name: Build and Push Docker Image
        if: ${{ startsWith(github.event.head_commit.modified, 'FirstApp/') || startsWith(github.event.head_commit.modified, 'SecondApp/') || startsWith(github.event.head_commit.modified, 'Modules/') }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REPOSITORY: shahid199578/monorepo
        run: |
          if [[ ${{ startsWith(github.event.head_commit.modified, 'Modules/') }} == 'true' ]]; then
            cp -r Modules/* FirstApp/
            cp -r Modules/* SecondApp/
          fi

          echo "::set-env name=IMAGE_TAG::${{ github.sha }}"
          docker buildx create --use
          docker buildx build --platform linux/amd64 --tag ${{ env.DOCKER_REPOSITORY }}:${{ env.IMAGE_TAG }} ./FirstApp
          docker buildx build --platform linux/amd64 --tag ${{ env.DOCKER_REPOSITORY }}:${{ env.IMAGE_TAG }} ./SecondApp
          docker login --username ${{ env.DOCKER_USERNAME }} --password ${{ env.DOCKER_PASSWORD }}
          docker push ${{ env.DOCKER_REPOSITORY }}:${{ env.IMAGE_TAG 
          
          github
